---
version: '3'
services:
    wordpress:
        image: wordpress
        ports:
            - 8080:80
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=myPassw0rd
            - WORDPRESS_DB_NAME=wp
            - WORDPRESS_TABLE_PREFIX=wp_
        volumes:
            - ./src/:/var/www/html/wp-content/plugins/social-app-login

    db:
        image: percona
        environment:
            - MYSQL_ROOT_PASSWORD=myPassw0rd


